version: '3.9'

services:
  db:
    image: postgres:15
    container_name: web_autelix-db-1
    volumes:
      - web_autelix_pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped

  web:
    build: .
    container_name: web_autelix-web-1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always

volumes:
  web_autelix_pgdata:
