# Generated by Django 5.2.4 on 2025-07-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статьи | Кейсы', 'verbose_name_plural': 'Статьи | Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Решения', 'verbose_name_plural': 'Решении'},
        ),
    ]
